name: Python CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Récupère le code du repo
      - uses: actions/checkout@v4

      # Installer Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # Installer pytest
      - name: Install dependencies
        run: pip install pytest

      # Lancer le script Python
      - name: Run job.py
        run: python job.py

      # Lancer les tests unitaires
      - name: Run tests
        run: pytest -v
